Repository Jeremylazm/AppSistemaTutoria, pull requests merged in 2021-09, with the labels that each got.

#61 Tecla ENTER para iniciar sesión
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/P_InicioSesion.Designer.cs
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/P_InicioSesion.cs
Labels: improvements

#63 Warning añadido al cerrar el formulario EditarPerfilEstudiante
  .vs/slnx.sqlite
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/P_EditarPerfilEstudiante.cs
Labels: enhancement

#65 Warnings añadidos al cerrar los formularios EditarPerfil
  .vs/slnx.sqlite
  Proyecto Final/AppSistemaTutoria/CapaDatos/D_Docente.cs
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/P_EditarPerfilDirector.cs
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/P_EditarPerfilDocente.cs
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/P_EditarPerfilEstudiante.cs
Labels: enhancement

#71 Corrección al cargar imagen predeterminada
  .vs/slnx.sqlite
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/CapaPresentaciones.csproj
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/P_DatosDocente.Designer.cs
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/P_DatosEstudiante.cs
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/P_EditarPerfilEstudiante.cs
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/Program.cs
  Proyecto Final/AppSistemaTutoria/CapaPresentaciones/Properties/licenses.licx
Labels: bug 🐞

#128 Readme: Screenshots director escuela agregados
  README.md
Labels: documentation

#129 Readme: screenshot BD actualizada
  README.md
  Screenshots/BaseDatos.png
  Screenshots/BaseDeDatos.png
Labels: documentation
